config/routes.rb
Semjo::Application.routes.draw do

  
  namespace :admin do
  
    resources :articles do
      member do 
        get :preview
      end
    end
  
    resources :pages do
      member do
        get :preview
      end 
    end
    
    resources :sessions

  end
  
  resources :articles
  resources :pages
  
  match '/admin' => redirect("/admin/articles")
  match '/feed.:format', :to => 'articles#feed'
  root :to => 'home#show'
  
end

app/views/admin/pages/_form.erb
<%= form_for( [:admin, @page] ) do |f| %>
	<p>Title: <%= f.text_field :title %></p>
<% unless @page.new_record? %>
	<p>Permalink: <%= f.text_field :permalink %> </p>
<% end %>
	<p>
		Content: (<%= link_to "textile", "http://redcloth.org/hobix.com/textile/quick.html"%> markup)<br/>
	  <%= f.text_area :content, :cols => 60 %>
	</p>
	<p>Published? <%= f.check_box :is_published?, {}, true, false %></p>
	<br /><%= f.submit "save" %>
<% end %>

app/views/admin/pages/_page.erb
<tr>
  <td><%= page.title %> </td>
  <td><%= page.permalink %> </td>
  <td><%= page.created_at.strftime(Time::DATE_FORMATS[:date_and_time]) %></td>
  <td><%= page.published_at.strftime(Time::DATE_FORMATS[:date_and_time]) if page.published_at%></td>
  <td><%= link_to "edit", edit_admin_page_path(page) %></td>
  <td><%= button_to 'delete', admin_page_path(page), :method => :delete, :confirm => "are you sure?" %></td>
</tr>

app/views/admin/pages/edit.erb
<h1>Editing Page: <%= @page.title %></h1>

<%= render :partial => "form" %>

<br/>
<%= link_to "preview", :action => 'preview'%>

app/views/admin/pages/index.erb
<h1>Pages</h1>

<%= link_to "create a new page", new_admin_page_path %>

<table>
  <tr><th>title</th><th>permalink</th><th>created at</th><th>published at</th><th>edit</th><th>delete</th></tr>
  <% @pages.each do |p| %>
  	<%= render :partial => 'page', :object => p %>
  <%end%>
</table>

app/views/admin/pages/new.erb
<h1>Make a new page</h1>

<%= render :partial => "form" %>