config/routes.rb
Semjo::Application.routes.draw do

  
  namespace :admin do
  
    resources :articles do
      member do 
        get :preview
      end
    end
  
    resources :pages do
      member do
        get :preview
      end 
    end
    
    resources :sessions

  end
  
  resources :articles
  resources :pages
  
  match '/admin' => redirect("/admin/articles")
  match '/feed.:format', :to => 'articles#feed'
  root :to => 'home#show'
  
end

app/models/article.rb
class Article < CouchRest::Model::Base
  
  include ContentModels

  define_properties_and_views 
  define_validations_and_callbacks
  
  define_publishing_related_methods
  define_permalink_related_methods
          
  proxied_by :blog
          
                   
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  
  before_filter :get_article_by_permalink, :only => [:edit, :update, :destroy, :preview]
  
  def preview
    render :template => "articles/show", :layout => 'articles'
  end
  
  def index
    @articles = @blog.articles.by_created_at.descending
  end
  
  def new
    @article = @blog.articles.new
  end

  def edit
  end
  
  def update   
    update_article
  end
  
  def create
    @article = @blog.articles.new
    update_article
  end
    
  def destroy
    @article.destroy
    redirect_to admin_articles_path
  end
  
  private
  
    def update_article
      @article.set_published( params["article"]["is_published"]=="true", session[:account])
      @article.set_permalink( params["article"]["permalink"] ) if params["article"]["permalink"]
      
      if @article.update_attributes(params[:article])
        redirect_to edit_admin_article_path(@article.permalink)
      else
         flash[:notice] = 'save failed'
         redirect_to :back
      end
    end
  
    def get_article_by_permalink
      @article = @blog.articles.by_permalink(:key => params[:id]).first      
      render :file => "#{Rails.root.to_s}/public/404.html", :status => 404 and return false unless @article
      Rails.logger.debug("got article")
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :get_most_recent_article, :only => [:index, :show, :feed]
  before_filter :get_article_by_permalink, :only => [:show]

  # show an article. Don't need to be logged in, but don't allow viewing of unpublished articles.
  def show
    fresh_when(:last_modified => @article.updated_at, :public => true, :etag => @article) if Rails.env.production?
  end

  def index
    if @most_recent_article
      if (!Rails.env.production?) || stale?(:last_modified => @most_recent_article.updated_at, :public => true, :etag => @most_recent_article)
        @page = params[:page].to_i || 1
        @page = 1 if @page < 1
        @articles = @blog.articles.by_published_at.descending.page(@page).per(@blog.articles_per_page)
      end
    end
  end

  def feed
    if (!Rails.env.production?) || stale?(:last_modified => (@most_recent_article ? @most_recent_article.updated_at : Time.now), :public => true, :etag => @most_recent_article)
      # At the moment, only provide the 10 latest articles in the feed.
      @articles = @blog.articles.by_published_at.descending.limit(10)
      render :layout => false
    end
  end

  private

    def get_article_by_permalink
      @article = @blog.articles.by_permalink(:key => params[:id]).first

      unless @article && @article.is_published?
        render :template => "404.erb", :status => 404, :layout => 'pages' and return false
      end
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def full_article_url(article, protocol = "http")
    "#{protocol}://#{@blog.canonical_url}/articles/#{article.permalink}"
  end

  def pagination_links
    pagination_links_html = ""

    if @page !=1
		  pagination_links_html += '<span class="newer_articles">' + link_to( h("< newer articles"), {:page => @page-1}) + '</span>'
		end

		if @total_articles > @per_page * @page
	    pagination_links_html += '<span class="older_articles">' + link_to( h("older articles >"), {:page => @page+1}) + '</span>'
	  end

	  return pagination_links_html
  end

  # make an article tag with the name passed in (e.g. :div). The about parameter is only required if there are multiple articles on the page, in which case it should be the url of the article in question.
  # If there's only one, it will default to the page's url.
  def rdfa_article_tag(tag_name, html_options = {}, about = nil, &block)
    article_options = {}
    article_options = {:about => about} if about
    article_options.merge!(html_options)
    content_tag(tag_name, article_options, {}, &block)
  end

  # make a title tag (e.g. :h2), and the content to go in the title.
  def rdfa_title_tag(tag_name, title_content)
    content_tag(tag_name, {"property" => "dc:title"}) do
      title_content
    end
  end

  # make an author tag (e.g. :div), and the personal uri and display name of the article's author
  def rdfa_author_tag(tag_name, personal_uri, display_name)
    content_tag(tag_name, {"rel" => "dc:creator", "resource" => personal_uri} ) do
      h(display_name)
    end
  end

  # make a date tag with the name passed in (e.g. :div), and the date passed.
  def rdfa_date_tag(tag_name, date, time_format = "%d %b %Y")
    content_tag(tag_name, {"property" => "dc:date", "datatype"=>"xsd:dateTime", "content" => date.xmlschema} ) do
      date.strftime(time_format)
    end
  end
end

app/views/admin/articles/_article.erb
<tr>
  <td><%= article.title %> </td>
  <td><%= article.permalink %> </td>
  <td><%= article.created_at.strftime(Time::DATE_FORMATS[:date_and_time]) %></td>
  <td><%= article.published_at.strftime(Time::DATE_FORMATS[:date_and_time]) if article.published_at %></td>
  <td><%= link_to "edit", edit_admin_article_path(article) %></td>
  <td><%= button_to 'delete', admin_article_path(article), :method => :delete, :confirm => "are you sure?" %></td>
</tr>

app/views/admin/articles/_form.erb
<%= form_for [:admin, @article]  do |f| %>
	<p>Title: <%= f.text_field :title %></p>
  <% unless @article.new_record? %>
  	<p>Permalink: <%= f.text_field :permalink %> </p>
  <% end %>
	<p>
		Content: (<%= link_to "textile", "http://redcloth.org/hobix.com/textile/quick.html"%> markup)<br/>
	  <%= f.text_area :content, :cols => 60 %>
	</p>
	<p>Published? <%= f.check_box :is_published?, {}, true, false %></p>
	<br /><%= f.submit "save" %>
<% end %>

app/views/admin/articles/edit.erb
<h1>Editing Article: <%= @article.title %></h1>

<%= render :partial => "form" %>

<br/>
<%= link_to "preview", :action => 'preview'%>

app/views/admin/articles/index.erb
<h1>Articles</h1>

<%= link_to "create a new article", new_admin_article_path %>

<table>
  <tr><th>title</th><th>permalink</th><th>created at</th><th>published at</th><th>edit</th><th>delete</th></tr>
  <% @articles.each do |a| %>
  	<%= render :partial => 'article', :object => a %>
  <%end%>
</table>

app/views/admin/articles/new.erb
<h1>Make a new article</h1>

<%= render :partial => "form" %>